FROM ubuntu:25.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    clang-20 \
    gcc-15 \
    g++-15 \
    cmake \
    ninja-build \
    ccache \
    scons \
    python3 \
    valgrind \
    git \
    ca-certificates \
    libc6-dbg \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/clang-20 /usr/local/bin/clang && \
    ln -s /usr/bin/clang++-20 /usr/local/bin/clang++

WORKDIR /workspace